name: Production
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
  push:
    branches:
      - main

jobs:
  Unit-Test:
    env:
      PUBLIC_SUPABASE_URL: https://qtrjysvownlgrjolkgvs.supabase.co
      PUBLIC_SUPABASE_ANON_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF0cmp5c3Zvd25sZ3Jqb2xrZ3ZzIiwicm9sZSI6ImFub24iLCJpYXQiOjE2Nzc4Nzg0NTUsImV4cCI6MTk5MzQ1NDQ1NX0.gk_tihxLVk-eE0R9SxzINsA17PJKWCRrql24nZKC6uU
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Run Unitest tests
        run: npm run test:unit

 Integration-Tests:
    needs: [Unit-Test]
    env:
      PUBLIC_SUPABASE_URL: https://qtrjysvownlgrjolkgvs.supabase.co
      PUBLIC_SUPABASE_ANON_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF0cmp5c3Zvd25sZ3Jqb2xrZ3ZzIiwicm9sZSI6ImFub24iLCJpYXQiOjE2Nzc4Nzg0NTUsImV4cCI6MTk5MzQ1NDQ1NX0.gk_tihxLVk-eE0R9SxzINsA17PJKWCRrql24nZKC6uU
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npx playwright test
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

  Deploy-Production:
    needs: [Unit-Test, Integration-Tests]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
